General:
  Arena-enabled-on-creation: true
  Out-of-arena-damage: true
  Out-of-arena-interference: false
Region:
  Make-corners-precise-on-creation: true
  Visible: true
  Visibility-period: 4
Task:
  Delay: 10
  Period: 10
  Enabled: true
Messages:
  Join-arena: true
  Leave-arena: true
  Death-in-arena: true
