name: PVPArena
version: '1.1'
main: me.loryyyy.pvparena.PVPArena
api-version: '1.20'
description: a plugin that allows players to create arena in the world where to fight until death.
author: Loryyyy
commands:
  arena:
    description: create and manage PVP arenas around the world
    usage: /arena
    aliases: arn
permissions:
  arena.set:
    description: allows a player to create and manage arenas
  arena.enable:
    description: allows a player to enable or disable arenas and the arena join/leave check
  arena.info:
    description: allows a player to see the info about all arenas
  arena.which:
    description: allows a player to know in which arena they're in (/arena)
  arena.configs-reload:
    description: allows a player to reload all the configs of this plugin (/arena confReload)
  arena.reload:
    description: allows a player to reload this plugin (/arena reload)
  arena.*:
    description: equivalent to every permission stated above